spring.application.name=shoppinglist

spring.datasource.url=jdbc:postgresql://localhost:5432/shoppinglist
spring.datasource.username=viggojohnsson
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true