spring.application.name=shoppinglist

spring.datasource.url=jdbc:postgresql://localhost:5432/shoppinglist
spring.datasource.username=viggojohnsson
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

vapid.public.key=BDhxI6e-UBpAr2OK2WKeuOb6oW9LinJ2xwqIfBJ2nRQNhQnV8Mp2DvrUAwWk0IEj4FT9iuXk3s8OBcpFgfpmivQ
vapid.private.key=_M106DzLcATLxRKcn5nMxgWHSpsu7hjJTXVPAktSznU
vapid.subject=mailto:viggo.johnsson1gmail.com

jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000